name: 'my-Dockerbuild'

author: 'murali'

description: 'Build, Tag and Push images to Registry'

inputs:
  image_name: 
    description: "Docker Image Name"
  image_tag:
    description: "Docker Image Tag"

runs:
  using: 'docker'
  image: 'Dockerfile'
  args: 
    - ${{ inputs.image_name }}
    - ${{ inputs.image_tag }}

branding:
  icon: 'upload-cloud'  
  color: 'blue'
