name: 'my-Dockerbuild'

author: 'murali'

description: 'Build, Tag and Push images to Registry'

inputs:
  image_name: 
    description: "Docker Image Name"
  image_tag:
    description: "Docker Image Tag"
  aws-secret-access-key:
    description: 'AWS credentials used to login to eks.'
    required: true
  aws-access-key-id:
    description: 'AWS credentials used to login to eks.'
    required: true
  aws-region:
    description: 'AWS region to use (default: us-west-2)'
    required: true
    default: us-west-2
  cluster-name:
    description: 'EKS cluster name.'
    required: true
  cluster-role-arn:
    description: 'EKS cluster admin role arn.'
    required: false
  config-files:
    description: 'Comma separates list of helm values files.'
    required: false
  namespace:
    description: 'Kubernetes namespace to use.'
    required: false
  values:
    description: 'Comma separated list of value sets for helms. e.x: key1=value1,key2=value2'
    required: false
  name:
    description: 'Name of the helm deploy.'
    required: true
  chart-path:
    description: 'The path of the chart.'
    required: true
    default: 'helm/'
  timeout:
    description: 'Timeout for the job.'
    required: true
    default: 0
  update-deps:
    description: 'Update chart dependencies'
    required: false
    default: "true"
  atomic:
    description: "Defines if helm will rollback in case of failure"
    required: false
    default: "false"
  force:
    description: "Force resource updates through a replacement strategy"
    required: false
    default: "false"  
outputs:
  image_url:
    description: "Docker image info"

runs:
  using: 'docker'
  image: 'Dockerfile'
  args: 
    - ${{ inputs.image_name }}
    - ${{ inputs.image_tag }}
  env:
      AWS_REGION: ${{ inputs.aws-region }}
      AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
      AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
      CLUSTER_NAME: ${{ inputs.cluster-name }}
      CLUSTER_ROLE_ARN: ${{ inputs.cluster-role-arn }}
      DEPLOY_CONFIG_FILES: ${{ inputs.config-files }}
      DEPLOY_NAMESPACE: ${{ inputs.namespace }}
      DEPLOY_VALUES: ${{ inputs.values }}
      DEPLOY_NAME: ${{ inputs.name }}
      DEPLOY_CHART_PATH: ${{ inputs.chart-path }}
      DEPLOY_ATOMIC:  ${{ inputs.atomic }}
      DEPLOY_FORCE:  ${{ inputs.force }}        
      TIMEOUT: ${{ inputs.timeout }}
      UPDATE_DEPS: ${{ inputs.update-deps }}

branding:
  icon: 'upload-cloud'  
  color: 'blue'
